// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdRL9-WlIJlshIcARyyFchXrkNcEpJS90',
    appId: '1:394246049460:web:d6d44fe376d943e55a11e1',
    messagingSenderId: '394246049460',
    projectId: 'auth-eb2cf',
    authDomain: 'auth-eb2cf.firebaseapp.com',
    storageBucket: 'auth-eb2cf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHuwHlOUvBop67VngaltNBjxXxbdRpMQg',
    appId: '1:394246049460:android:b75fd555bed44f125a11e1',
    messagingSenderId: '394246049460',
    projectId: 'auth-eb2cf',
    storageBucket: 'auth-eb2cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8KNpwKHcFpthV9UvBWNtVsmNesxJNEgI',
    appId: '1:394246049460:ios:8e3c21c18037656e5a11e1',
    messagingSenderId: '394246049460',
    projectId: 'auth-eb2cf',
    storageBucket: 'auth-eb2cf.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8KNpwKHcFpthV9UvBWNtVsmNesxJNEgI',
    appId: '1:394246049460:ios:8e3c21c18037656e5a11e1',
    messagingSenderId: '394246049460',
    projectId: 'auth-eb2cf',
    storageBucket: 'auth-eb2cf.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );
}
